from django.urls import path
from .import views
urlpatterns = [
    path('', views.home, name='home'),  # Homepage
    path('membershipannual/', views.memberships, name='membershipannual'),
    path('dietplan/', views.diet_plan, name='dietplan'),
    path('classes/', views.fitness_classes, name='all_classes'),  # Correct URL name
    path('classes/<str:category_name>/', views.fitness_classes, name='category_classes'),
    path('training/', views.training, name='training'),
    path('aboutus/', views.about_us, name='aboutus'),
    path('careers/', views.careers, name='careers'),
    path('protien/', views.products, name='protien'),
    path('login/', views.loginuser, name='login'), 
    path('register/',views.register,name='register'),
    path('signout/',views.signout,name='signout'),
    path('supplementCategory/<int:id>/',views.category,name='supplementCategory'),
    path('cards/<int:id>/',views.cards,name='cards'),
    path('crud/', views.crud, name='crud_operations'),
    path('showdetails/', views.showdetails, name='showdetails'),
    path('edit/<int:id>/', views.editproduct, name='edit'),
    path('delete/<int:id>/',views.deleteproduct),
    path('addtocart/<int:id>/', views.addtocart, name='addtocart'),
    path('deleteproductcrud/<int:id>/',views.deleteproductcrud,name='deleteproductcrud'),
    path('viewcart/', views.viewcart, name='viewcart'),
    path('updateqty/<qv>/<id>/',views.updateqty),
    path('searchdata', views.searchdata, name='searchdata'),  # Search page
    path('remove/<int:id>',views.remove,name='remove'),
    path('checkout/',views.Processedtocheck,name='checkout'),
    path('membershipmonthly',views.membershipmonthly,name='membershipmonthly'),
    path('makepayment/', views.makepayment, name='makepayment'),
    path('paymentfailed/',views.paymentfailed,name='paymentfailed'),
    path('paymentsuccess/',views.paymentsuccess,name='paymentsuccess'),
    path('edit-address/<int:id>/', views.edit_address, name='edit_address'),
    path('edit-address/<int:id>/', views.edit_address, name='edit_address'),
    path('membership/<int:id>/', views.membership_processed_view, name='membership_list'),
    path('membershipmonthly/<int:id>/', views.membership_processed_view_month, name='membership_lists'),
    path('membership_form/', views.membership_processed_view, name='membership_form'),
    path('membershipprocessedtocheckout/<int:id>/',views.membership_processedtocheckout,name='membershipprocessedtocheckouts'),
    path('membershipprocessedtocheckoutmonthly/<int:id>/', views.membership_processedtocheckout_monthly, name='membershipprocessedtocheckout'),
    path('membershipmonthly/<int:id>/', views.membership_processed_view_month, name='membership_lists'),
    path('membershipprocessedtocheckoutmonthly/<int:id>/', views.membership_processedtocheckout_monthly, name='membershipprocessedtocheckout_monthly'),
    path('orders/',views.orders,name='orders'),
    path('myorders/',views.myorders,name='myorders'),
    path('orders/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('remove/<int:order_id>/', views.remove_order, name='remove_order'),
    path('paymentmembership/',views.paymentmembership,name='paymentmembership'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('edit-profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('my-addresses/', views.my_addresses, name='my_addresses'),
    path('drf_crud/',views.crudapi.as_view()),
    path('profile/', views.profile_view, name='profile'),
    path('forgetpassword/',views.forgetpassword,name='forgetpassword'),
    path('verifyotp/',views.verifyotp,name='verifyotp'),
    path('resetpassword/',views.resetpassword,name='resetpassword'),
    path('membership_checkout/<int:id>/', views.membership_processedtocheckout, name='membership_processedtocheckout'),
    path('membership_checkout_monthly/<int:id>/', views.membership_processedtocheckout_monthly, name='membership_processedtocheckout_monthly'),
    path('weightlossplan/',views.weightlossplan,name='weightlossplan'),
    path('muselloss/',views.muselloss,name='muselloss'),
    path('healthlyplan/',views.healthlyplan,name='healthlyplan'),

]

