# Generated by Django 5.1.4 on 2025-01-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customerer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField()),
                ('custName', models.CharField(max_length=200)),
                ('custAddress', models.TextField()),
                ('custContact', models.BigIntegerField()),
                ('custEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GymProductses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=200)),
                ('prodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prodDesc', models.TextField()),
                ('prodCat', models.CharField(max_length=200)),
            ],
        ),
    ]
