# Generated by Django 5.1.4 on 2025-01-11 22:45

import FitnessGYM.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=200, validators=[FitnessGYM.models.validation_Email])),
                ('customerPhone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentId', models.IntegerField()),
                ('equipmentName', models.CharField(max_length=100)),
                ('equipmentType', models.CharField(max_length=50)),
                ('equipmentCondition', models.CharField(max_length=50)),
                ('equipmentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programId', models.IntegerField()),
                ('programName', models.CharField(max_length=100)),
                ('programDuration', models.IntegerField()),
                ('programLevel', models.CharField(max_length=50)),
                ('programDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershipId', models.IntegerField()),
                ('membershipName', models.CharField(max_length=100)),
                ('membershipPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplementName', models.CharField(max_length=100)),
                ('supplementPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplementDescription', models.TextField()),
                
            ],
        ),
        migrations.CreateModel(
            name='SupplementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainerId', models.IntegerField()),
                ('trainerName', models.CharField(max_length=100)),
                ('trainerSpecialization', models.CharField(max_length=100)),
                ('trainerExperience', models.IntegerField()),
                ('trainerEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Customerer',
        ),
        migrations.DeleteModel(
            name='GymProductses',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessGYM.gymmembership'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplementCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessGYM.supplementcategory'),
        ),
    ]
