# Generated by Django 5.1.4 on 2025-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0002_customer_equipment_fitnessprogram_gymmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='supplementImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='supplementRating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='supplementName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='supplementPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
