# Generated by Django 5.1.4 on 2025-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
