# Generated by Django 5.1.4 on 2025-01-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0007_cart_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='FitnessGYM.supplement'),
        ),
    ]
