# Generated by Django 5.1.4 on 2025-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0008_alter_cart_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='delete_details',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
