# Generated by Django 5.1.4 on 2025-02-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0013_clubexperience_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubExperience',
        ),
    ]
