# Generated by Django 5.1.4 on 2025-02-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0014_delete_clubexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membershipmonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Core', 'Core'), ('Premier', 'Premier'), ('Executive', 'Executive')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
