# Generated by Django 5.1.4 on 2025-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0016_membershipprocessedtocheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipmonth',
            name='choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
