# Generated by Django 5.1.4 on 2025-02-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0017_membershipmonth_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
