# Generated by Django 5.1.4 on 2025-02-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0018_membership_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='choice',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('Premier', 'Premier'), ('Executive', 'Executive')], max_length=50, null=True),
        ),
    ]
