# Generated by Django 5.1.4 on 2025-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0019_alter_membership_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipmonth',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
