# Generated by Django 5.1.4 on 2025-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0020_alter_membershipmonth_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
