# Generated by Django 5.1.4 on 2025-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0025_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
