# Generated by Django 5.1.4 on 2025-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0027_membershipprocessedtocheck_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
