# Generated by Django 5.1.4 on 2025-02-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0028_membershipprocessedtocheck_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='plan_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
