# Generated by Django 5.1.4 on 2025-02-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0029_membershipprocessedtocheck_plan_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtocheck',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessGYM.membership'),
        ),
        migrations.AddField(
            model_name='processedtocheck',
            name='membership_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessGYM.membershipmonth'),
        ),
    ]
