# Generated by Django 5.1.4 on 2025-02-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0030_processedtocheck_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipprocessedtocheck',
            old_name='membership',
            new_name='membership_yearly',
        ),
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='membership_monthly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessGYM.membershipmonth'),
        ),
    ]
