# Generated by Django 5.1.4 on 2025-03-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0031_rename_membership_membershipprocessedtocheck_membership_yearly_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessprogram',
            old_name='programDuration',
            new_name='programDurations',
        ),
    ]
