# Generated by Django 5.1.6 on 2026-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0032_rename_programduration_fitnessprogram_programdurations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={'ordering': ['supplementName']},
        ),
        migrations.AddField(
            model_name='supplement',
            name='stock',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
