# Generated by Django 5.1.6 on 2026-09-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessGYM', '0034_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['tier', 'price']},
        ),
        migrations.AlterModelOptions(
            name='membershipmonth',
            options={'ordering': ['tier', 'price']},
        ),
        migrations.AddField(
            model_name='membership',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membershipmonth',
            name='tier',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='pending_monthly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_upgrades', to='FitnessGYM.membershipmonth'),
        ),
        migrations.AddField(
            model_name='membershipprocessedtocheck',
            name='pending_yearly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_upgrades', to='FitnessGYM.membership'),
        ),
    ]
